INSERT INTO categories VALUES
	(1, 'Language'),
	(2, 'Environment'),
	(3, 'Design'),
	(4, 'Management'),
	(5, 'Soft_Skills');


INSERT INTO skills VALUES
	(1, 'C#', 'This my favorite language, used with Unity or .NET framework.', 'skill01.png', 1),
	(2, 'C', 'One year of expertise with this language, I used it for several algorithms.', 'skill02.png', 1),
	(3, 'C++', 'One year of expertise with this language, I used it for several algorithms..', 'skill03.png', 1),
	(4, 'JavaScript', 'Four years of expertise with this language, I used it with Phaser or for several websites.', 'skill04.png', 1),
	(5, 'HTML', 'Five years of expertise with this language, I used it for several websites, with or without Bootstrap.', 'skill05.png', 1),
	(6, 'CSS', 'Five years of expertise with this language, I used it for several websites.', 'skill06.png', 1),
	(7, 'PHP', 'Four years of expertise with this language, I used it for several websites, using CRUD system.', 'skill07.png', 1),
	(8, 'SQL', 'Four years of expertise with this language, I used it to create and handle database.', 'skill08.png', 1),
	(9, 'Python', 'I learned this language alone during one month to extend my skills about development languages.', 'skill09.png', 1),
	(10, 'Unity', 'I learned Unity during 4 years and it is my favorite video games engine. I created games for desktop, web, mobile, XBox and Nintendo Switch.', 'skill10.png', 2),
	(11, 'Unreal Engine', 'I used UE4 for several video game projects and for VR games.', 'skill11.png', 2),
	(12, 'Phaser', 'I used Phaser for a video game using JavaScript', 'skill12.png', 2),
	(13, 'PhpMyAdmin', 'I used PhpMyAdmin to handle datas with websites. I learned Merise method and CRUD with it.', 'skill13.png', 2),
	(14, 'Postman', 'I learned how to use Postman alone to handle APIs.', 'skill14.png', 2),
	(15, 'Visual Studio', 'I develop code using Visual Studio.', 'skill15.png', 2),
	(16, 'Construct', 'I created my first video games using Construct.', 'skill16.png', 2),
	(17, 'Tools Office 365', 'I know how to use almost all tools of Office 365 : Excel, Word, SharePoint, Forms, Powerpoint ...', 'skill17.png', 2),
	(18, 'Paint.NET', 'I am a little in love with Paint.NET to create pictures for my video games or presentations.', 'skill18.png', 2),
	(19, 'PyCharm', 'I learned how to use PyCharm when I learned how to develop in Python.', 'skill19.png', 2),
	(20, 'Documentation', 'I know how to write documentation, about Game Design or UML.', 'skill20.png', 3),
	(21, 'Level Design', 'I used this skill in my video games to organize the flow relative to the gameplay.', 'skill21.png', 3),
	(22, 'UI/UX', 'I used this skill in my video games or websites to organize the HUD and improve the experience of users.', 'skill22.png', 3),
	(23, 'VR', 'I created many games using UE4 in virtual reality.', 'skill23.png', 3),
	(24, 'Prototype', 'I created many prototype of video games to show technical gameplay above art design.', 'skill24.png', 3),
	(25, 'Narrative Design', 'I created many games with a story and a narrative pattern.', 'skill25.png', 3),
	(26, 'Serious Game', 'I created many games for a serious goal with serious stakes.', 'skill26.png', 3),
	(27, 'Comprehension of developement jobs', 'How to work with other with coworkers which are doing an other job.', 'skill27.png', 4),
	(28, 'JIRA', 'A tool to work with other people.', 'skill28.png', 4),
	(29, 'GitHub', 'A versionning tool to merge work with other people.', 'skill29.png', 4),
	(30, 'Trello', 'A tool to work with other people.', 'skill30.png', 4),
	(31, 'English', 'A mastery of english.', 'skill31.png', 4),
	(32, 'SCRUM', 'I used the agile developement SCRUM many times for projects.', 'skill32.png', 4),
	(33, 'Project Management', 'I know how to plan project with adequate tools.', 'skill33.png', 4),
	(34, 'CleanCode', 'I know how to code with proper methods : Clean Code.', 'skill34.png', 4),
	(35, 'GreanCode', 'I know how to code with respect of the planet : Green Code.', 'skill35.png', 4),
	(36, 'Collaborative', '', '', 5),
	(37, 'Flexible', '', '', 5),
	(38, 'Autonomous', '', '', 5),
	(39, 'Organized', '', '', 5),
	(40, 'Proactive', '', '', 5),
	(41, 'Enthusiastic', '', '', 5),
	(42, 'Creative', '', '', 5),
	(43, 'Curious', '', '', 5),
	(44, 'Analytic', '', '', 5),
	(45, 'Adaptative', '', '', 5);